import { AspectRatio, ImageResolution, ModelType } from './types';
import type { StickerStyle } from './types';
import { Palette, Zap, Star, Monitor, Ghost, PenTool } from 'lucide-react';

export const STICKER_STYLES: StickerStyle[] = [
  {
    id: 'classic-cartoon',
    name: 'Classic Cartoon',
    label_zh: '经典卡通',
    promptModifier: 'vibrant flat cartoon sticker, thick bold black outlines, simple shading, vector art style, cute and expressive',
    previewColor: 'bg-yellow-400',
  },
  {
    id: 'kawaii-chibi',
    name: 'Kawaii Chibi',
    label_zh: '可爱Q版',
    promptModifier: 'adorable kawaii chibi sticker, pastel colors, giant sparkling eyes, soft rounded shapes, bubbly aesthetic, white outline',
    previewColor: 'bg-pink-400',
  },
  {
    id: '3d-glossy',
    name: '3D Glossy',
    label_zh: '3D光泽',
    promptModifier: '3D rendered toy sticker, plastic glossy texture, claymation style, soft studio lighting, cute character design, volumetric',
    previewColor: 'bg-blue-400',
  },
  {
    id: 'vintage-badge',
    name: 'Vintage Badge',
    label_zh: '复古徽章',
    promptModifier: 'retro vintage sticker, muted color palette, textured paper feel, 70s badge style, distressed look, typography elements',
    previewColor: 'bg-orange-400',
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art',
    label_zh: '像素艺术',
    promptModifier: 'pixel art sticker, 8-bit retro game style, blocky details, limited color palette, clean edges, white outline',
    previewColor: 'bg-purple-400',
  },
  {
    id: 'watercolor',
    name: 'Watercolor',
    label_zh: '水彩画',
    promptModifier: 'watercolor painted sticker, artistic brush strokes, soft gradients, paper texture, dreamy and whimsical, hand-painted look',
    previewColor: 'bg-teal-400',
  },
  {
    id: 'neon-cyberpunk',
    name: 'Neon Cyberpunk',
    label_zh: '霓虹赛博',
    promptModifier: 'neon cyberpunk sticker, glowing lights, futuristic, dark background, synthwave colors, high contrast',
    previewColor: 'bg-fuchsia-600',
  },
  {
    id: 'paper-cutout',
    name: 'Paper Cutout',
    label_zh: '剪纸艺术',
    promptModifier: 'layered paper cutout style sticker, craft art, textured paper, depth shadows, handmade feel',
    previewColor: 'bg-orange-300',
  },
  {
    id: 'graffiti',
    name: 'Graffiti',
    label_zh: '街头涂鸦',
    promptModifier: 'urban graffiti sticker, spray paint texture, street art, drips, bold wildstyle, vibrant',
    previewColor: 'bg-lime-500',
  },
  {
    id: 'holographic',
    name: 'Holographic',
    label_zh: '全息镭射',
    promptModifier: 'holographic sticker, iridescent foil texture, metallic rainbow reflections, shiny, chromatic aberration',
    previewColor: 'bg-cyan-300',
  },
  {
    id: 'sketch',
    name: 'Pencil Sketch',
    label_zh: '铅笔素描',
    promptModifier: 'pencil sketch sticker, hand-drawn graphite, rough lines, artistic, monochrome or muted colors',
    previewColor: 'bg-stone-400',
  },
  {
    id: 'anime',
    name: 'Anime',
    label_zh: '日系动漫',
    promptModifier: 'anime manga sticker, cel shaded, vibrant, japanese animation style, expressive, clean lines',
    previewColor: 'bg-rose-400',
  },
  {
    id: 'flat-emoji',
    name: 'Flat Emoji',
    label_zh: '扁平表情',
    promptModifier: 'flat design emoji style, minimal vector, solid colors, UI icon aesthetic, simple shapes',
    previewColor: 'bg-yellow-300',
  },
  {
    id: 'impressionist',
    name: 'Impressionist',
    label_zh: '印象油画',
    promptModifier: 'oil painting sticker, thick brush strokes, impressionist style, textured canvas, artistic',
    previewColor: 'bg-amber-600',
  },
  {
    id: 'stained-glass',
    name: 'Stained Glass',
    label_zh: '彩色玻璃',
    promptModifier: 'stained glass sticker, mosaic pattern, vibrant translucent colors, black lead lines, geometric',
    previewColor: 'bg-emerald-600',
  },
  {
    id: 'psychedelic',
    name: 'Psychedelic',
    label_zh: '迷幻波普',
    promptModifier: 'psychedelic pop art sticker, swirling colors, trippy patterns, surreal, groovy, 60s style',
    previewColor: 'bg-violet-500',
  },
];

export const ASPECT_RATIOS = [
  { value: AspectRatio.SQUARE, label: 'Square (1:1)' },
  { value: AspectRatio.PORTRAIT, label: 'Portrait (3:4)' },
  { value: AspectRatio.LANDSCAPE, label: 'Landscape (4:3)' },
  { value: AspectRatio.WIDE, label: 'Wide (16:9)' },
];

export const RESOLUTIONS = [
  { value: ImageResolution.RES_1K, label: 'Standard (1K)' },
  { value: ImageResolution.RES_2K, label: 'High (2K) - Pro Only' },
  { value: ImageResolution.RES_4K, label: 'Ultra (4K) - Pro Only' },
];

export const AVAILABLE_FONTS = [
  { name: 'Standard', family: 'Fredoka, sans-serif' },
  { name: 'Comic', family: 'Bangers, cursive' },
  { name: 'Script', family: 'Pacifico, cursive' },
  { name: 'Sci-Fi', family: 'Orbitron, sans-serif' },
  { name: 'Horror', family: 'Creepster, cursive' },
  { name: 'Elegant', family: 'Abril Fatface, cursive' },
];

export const BACKGROUND_COLORS = [
  { name: 'White', value: 'white', class: 'bg-white border-slate-200' },
  { name: 'Black', value: 'black', class: 'bg-slate-900 border-slate-700' },
  { name: 'Red', value: 'pastel red', class: 'bg-red-500 border-red-600' },
  { name: 'Blue', value: 'pastel blue', class: 'bg-blue-500 border-blue-600' },
  { name: 'Green', value: 'pastel green', class: 'bg-green-500 border-green-600' },
  { name: 'Yellow', value: 'pastel yellow', class: 'bg-yellow-400 border-yellow-500' },
  { name: 'Pink', value: 'pastel pink', class: 'bg-pink-400 border-pink-500' },
  { name: 'Purple', value: 'pastel purple', class: 'bg-purple-500 border-purple-600' },
];

export const DEFAULT_REQUEST_CONFIG = {
  quantity: 1,
  model: ModelType.NANO_BANANA_2,
  aspectRatio: AspectRatio.SQUARE,
  resolution: ImageResolution.RES_1K,
  useFacialFeatures: true,
};

export const LANGUAGE_OPTIONS = [
  { code: 'en', label: 'English', shortLabel: 'EN' },
  { code: 'zh', label: '中文', shortLabel: '中文' },
  { code: 'es', label: 'Español', shortLabel: 'ES' },
  { code: 'fr', label: 'Français', shortLabel: 'FR' },
  { code: 'de', label: 'Deutsch', shortLabel: 'DE' },
  { code: 'ja', label: '日本語', shortLabel: '日本語' },
  { code: 'ko', label: '한국어', shortLabel: '한국어' },
  { code: 'pt', label: 'Português', shortLabel: 'PT' },
] as const;

export const PRESET_PROMPTS = {
  en: [
    "A cute baby fox",
    "A fleet of yellow submarines",
    "A robot eating pizza",
    "A magical tree house",
    "A cat wearing sunglasses"
  ],
  zh: [
    "一只可爱的小狐狸",
    "黄色潜艇舰队",
    "吃披萨的机器人",
    "神奇的树屋",
    "戴墨镜的猫"
  ],
  es: [
    "Un zorrito adorable",
    "Una flota de submarinos amarillos",
    "Un robot comiendo pizza",
    "Una casa del árbol mágica",
    "Un gato con gafas de sol"
  ],
  fr: [
    "Un adorable bébé renard",
    "Une flotte de sous-marins jaunes",
    "Un robot qui mange une pizza",
    "Une cabane magique dans les arbres",
    "Un chat avec des lunettes de soleil"
  ],
  de: [
    "Ein süßer kleiner Fuchs",
    "Eine Flotte gelber U-Boote",
    "Ein Roboter, der Pizza isst",
    "Ein magisches Baumhaus",
    "Eine Katze mit Sonnenbrille"
  ],
  ja: [
    "かわいい子ぎつね",
    "黄色い潜水艦の艦隊",
    "ピザを食べるロボット",
    "魔法のツリーハウス",
    "サングラスをかけた猫"
  ],
  ko: [
    "귀여운 아기 여우",
    "노란 잠수함 함대",
    "피자를 먹는 로봇",
    "마법의 나무 집",
    "선글라스를 낀 고양이"
  ],
  pt: [
    "Uma raposinha fofa",
    "Uma frota de submarinos amarelos",
    "Um robô comendo pizza",
    "Uma casa na árvore mágica",
    "Um gato usando óculos de sol"
  ]
};

export const TRANSLATIONS = {
  en: {
    title_suffix: "Craft",
    subtitle: "AI Generator",
    powered_by: "Powered by Gemini",
    hero_title_1: "Turn ideas into",
    hero_title_2: "Stickers",
    hero_desc: "Create unique, cartoon-style stickers in seconds using advanced AI. Just describe it, style it, and stick it!",
    
    prompt_label: "What do you want to create?",
    prompt_placeholder: "Enter one prompt per line to generate a batch...\nE.g.,\nA happy little fox\nA fleet of submarines",
    prompt_presets: "Try these:",
    
    style_label: "Choose a Style",
    style_custom_count: "Custom",
    style_custom_remove: "Remove style",
    style_import: "Create Custom Style",
    style_modifier: "Style Modifier",
    style_analyzed: "Analyzed Style Description",
    style_my: "MY",
    
    create_style_title: "Create New Style",
    style_desc_placeholder: "Describe the style (e.g. 'Watercolor, soft pastel colors, dreamy vibe')...",
    upload_reference: "Upload Reference Image (Optional)",
    btn_create_style: "Save Style",
    btn_creating_style: "Analyzing & Saving...",
    style_creation_error: "Please provide a description or an image to create a style.",
    style_image_analyzed: "Image analyzed successfully!",

    config_quantity: "Quantity",
    config_ratio: "Ratio",
    config_model: "Model",
    config_resolution: "Resolution",
    config_layout_mode: "Layout Mode",
    config_single_sticker: "Single Sticker",
    config_three_views: "Three Views (Sheet)",
    config_sticker_collection: "Sticker Collection",
    config_sticker_collection_count: "Stickers in one image",
    config_sticker_collection_hint: "Generate multiple small stickers together on one cohesive sheet.",
    config_sticker_border: "White Sticker Border",
    config_facial_features: "Generate Faces",
    
    text_section_title: "Text",
    background_section_title: "Background",
    text_enable: "Add Text?",
    text_input_placeholder: "Enter text, or leave blank for AI to choose",
    font_style: "FONT STYLE",
    text_border: "Add Text Border",
    bg_color: "Background Color",
    
    btn_generate: "Generate Stickers",
    btn_generating: "Crafting your stickers...",
    
    gallery_title: "Your Gallery",
    gallery_category_all: "All Styles",
    select_all: "Select All",
    deselect_all: "Deselect All",
    download_zip: "Download ZIP",
    selected: "Selected",
    zipping: "Zipping...",
    
    empty_gallery_title: "Ready to create?",
    empty_gallery_desc: "Enter a prompt above and choose a style to generate your first batch of custom stickers!",
    
    error_generic: "Something went wrong while generating stickers. Please try again.",
    
    sticker_details: "Sticker Details",
    created: "Created",
    download_png: "Download PNG",
    
    custom_style_name: "My Style",

    action_delete: "Delete",
    action_regenerate: "Regenerate / Remix",
    action_clear_image: "Clear Image",
    
    prompt_generator_title: "Prompt Generator",
    prompt_generator_placeholder: "Enter a category (e.g. 'Plants', 'Fast Food')",
    prompt_generator_btn: "Generate List",
    prompt_generator_use: "Use These",
    
    upload_image_title: "Upload to Gallery",
    upload_image_desc: "Add your own image to the gallery.",
    upload_image_classification: "Classification / Style",
    upload_image_prompt: "Description / Prompt",
    btn_upload: "Upload",
    btn_uploading: "Uploading...",
  },
  zh: {
    title_suffix: "工坊",
    subtitle: "AI 生成器",
    powered_by: "由 Gemini 驱动",
    hero_title_1: "将创意转化为",
    hero_title_2: "贴纸",
    hero_desc: "利用先进的 AI 技术，瞬间将创意转化为独特的卡通贴纸。只需描述、选择风格，即可生成！",
    
    prompt_label: "你想创作什么？",
    prompt_placeholder: "每行输入一个提示词以进行批量生成...\n例如：\n一只快乐的小狐狸\n一支潜艇舰队",
    prompt_presets: "试试这些：",
    
    style_label: "选择风格",
    style_custom_count: "自定义",
    style_custom_remove: "删除风格",
    style_import: "创建自定义风格",
    style_modifier: "风格描述",
    style_analyzed: "AI分析的风格描述",
    style_my: "我",

    create_style_title: "创建新风格",
    style_desc_placeholder: "描述风格 (例如 '水彩画，柔和的色彩，梦幻氛围')...",
    upload_reference: "上传参考图片 (可选)",
    btn_create_style: "保存风格",
    btn_creating_style: "正在分析并保存...",
    style_creation_error: "请提供风格描述或参考图片。",
    style_image_analyzed: "图片分析成功！",
    
    config_quantity: "数量 (每种)",
    config_ratio: "比例",
    config_model: "模型",
    config_resolution: "分辨率",
    config_layout_mode: "布局模式",
    config_single_sticker: "普通贴纸",
    config_three_views: "生成三视图 (设定图)",
    config_sticker_collection: "生成贴纸集合",
    config_sticker_collection_count: "每张小贴纸数量",
    config_sticker_collection_hint: "在一张图里生成多个统一风格的小贴纸。",
    config_sticker_border: "生成贴纸白边 (描边)",
    config_facial_features: "生成面部/表情",
    
    text_section_title: "文字",
    background_section_title: "背景",
    text_enable: "添加文字？",
    text_input_placeholder: "输入文字，留空则由 AI 自己决定",
    font_style: "字体风格",
    text_border: "添加文字描边",
    bg_color: "背景颜色",
    
    btn_generate: "生成贴纸",
    btn_generating: "正在制作贴纸...",
    
    gallery_title: "你的图库",
    gallery_category_all: "全部风格",
    select_all: "全选",
    deselect_all: "取消全选",
    download_zip: "下载 ZIP",
    selected: "已选择",
    zipping: "正在压缩...",
    
    empty_gallery_title: "准备好创作了吗？",
    empty_gallery_desc: "在上方输入提示词并选择一种风格，开始生成你的第一批专属贴纸！",
    
    error_generic: "生成贴纸时出现问题，请重试。",
    
    sticker_details: "贴纸详情",
    created: "创建时间",
    download_png: "下载 PNG",
    
    custom_style_name: "我的风格",

    action_delete: "删除",
    action_regenerate: "重绘 / 变体",
    action_clear_image: "清除图片",
    
    prompt_generator_title: "提示词生成器",
    prompt_generator_placeholder: "输入类别 (例如 '植物', '快餐')",
    prompt_generator_btn: "生成列表",
    prompt_generator_use: "使用这些",
    
    upload_image_title: "上传到图库",
    upload_image_desc: "将你自己的图片添加到图库中。",
    upload_image_classification: "分类 / 风格",
    upload_image_prompt: "描述 / 提示词",
    btn_upload: "上传",
    btn_uploading: "正在上传...",
  },
  es: {
    title_suffix: "Craft",
    subtitle: "Generador IA",
    powered_by: "Impulsado por Gemini",
    hero_title_1: "Convierte ideas en",
    hero_title_2: "Stickers",
    hero_desc: "Crea stickers únicos de estilo caricatura en segundos con IA avanzada.",
    prompt_label: "¿Qué quieres crear?",
    prompt_placeholder: "Escribe un prompt por línea para generar en lote...\nEj.:\nUn zorrito feliz\nUna flota de submarinos",
    prompt_presets: "Prueba estos:",
    style_label: "Elige un estilo",
    style_custom_count: "Personalizado",
    style_custom_remove: "Eliminar estilo",
    style_import: "Crear estilo personalizado",
    style_modifier: "Modificador de estilo",
    style_analyzed: "Descripción de estilo analizada",
    style_my: "MI",
    create_style_title: "Crear nuevo estilo",
    style_desc_placeholder: "Describe el estilo (ej. 'acuarela, colores pastel suaves, ambiente soñador')...",
    upload_reference: "Subir imagen de referencia (opcional)",
    btn_create_style: "Guardar estilo",
    btn_creating_style: "Analizando y guardando...",
    style_creation_error: "Proporciona una descripción o una imagen para crear un estilo.",
    style_image_analyzed: "Imagen analizada correctamente.",
    config_quantity: "Cantidad",
    config_ratio: "Relación",
    config_model: "Modelo",
    config_resolution: "Resolución",
    config_layout_mode: "Modo de diseño",
    config_single_sticker: "Sticker único",
    config_three_views: "Tres vistas",
    config_sticker_collection: "Colección de stickers",
    config_sticker_collection_count: "Stickers por imagen",
    config_sticker_collection_hint: "Genera varios stickers pequeños juntos en una lámina coherente.",
    config_sticker_border: "Borde blanco",
    config_facial_features: "Generar caras",
    text_section_title: "Texto",
    background_section_title: "Fondo",
    text_enable: "¿Agregar texto?",
    text_input_placeholder: "Escribe texto o deja vacío para que la IA elija",
    font_style: "Estilo de fuente",
    text_border: "Borde de texto",
    bg_color: "Color de fondo",
    btn_generate: "Generar stickers",
    btn_generating: "Creando stickers...",
    gallery_title: "Tu galería",
    gallery_category_all: "Todos los estilos",
    select_all: "Seleccionar todo",
    deselect_all: "Deseleccionar todo",
    download_zip: "Descargar ZIP",
    selected: "Seleccionados",
    zipping: "Comprimiendo...",
    empty_gallery_title: "¿Listo para crear?",
    empty_gallery_desc: "Escribe un prompt y elige un estilo para generar tu primera tanda de stickers.",
    error_generic: "Algo salió mal al generar stickers. Inténtalo de nuevo.",
    sticker_details: "Detalles del sticker",
    created: "Creado",
    download_png: "Descargar PNG",
    custom_style_name: "Mi estilo",
    action_delete: "Eliminar",
    action_regenerate: "Regenerar / Remix",
    action_clear_image: "Borrar imagen",
    prompt_generator_title: "Generador de prompts",
    prompt_generator_placeholder: "Ingresa una categoría (ej. 'Plantas', 'Comida rápida')",
    prompt_generator_btn: "Generar lista",
    prompt_generator_use: "Usar estos",
    upload_image_title: "Subir a galería",
    upload_image_desc: "Agrega tu propia imagen a la galería.",
    upload_image_classification: "Clasificación / Estilo",
    upload_image_prompt: "Descripción / Prompt",
    btn_upload: "Subir",
    btn_uploading: "Subiendo...",
  },
  fr: {
    title_suffix: "Craft",
    subtitle: "Générateur IA",
    powered_by: "Propulsé par Gemini",
    hero_title_1: "Transformez vos idées en",
    hero_title_2: "Stickers",
    hero_desc: "Créez en quelques secondes des stickers uniques de style cartoon avec l'IA.",
    prompt_label: "Que voulez-vous créer ?",
    prompt_placeholder: "Entrez un prompt par ligne pour générer un lot...\nEx. :\nUn petit renard joyeux\nUne flotte de sous-marins",
    prompt_presets: "Essayez ceci :",
    style_label: "Choisir un style",
    style_custom_count: "Personnalisé",
    style_custom_remove: "Supprimer le style",
    style_import: "Créer un style personnalisé",
    style_modifier: "Modificateur de style",
    style_analyzed: "Description de style analysée",
    style_my: "MON",
    create_style_title: "Créer un nouveau style",
    style_desc_placeholder: "Décrivez le style (ex. 'aquarelle, tons pastel, ambiance rêveuse')...",
    upload_reference: "Importer une image de référence (facultatif)",
    btn_create_style: "Enregistrer le style",
    btn_creating_style: "Analyse et enregistrement...",
    style_creation_error: "Ajoutez une description ou une image pour créer un style.",
    style_image_analyzed: "Image analysée avec succès.",
    config_quantity: "Quantité",
    config_ratio: "Format",
    config_model: "Modèle",
    config_resolution: "Résolution",
    config_layout_mode: "Mode de mise en page",
    config_single_sticker: "Sticker unique",
    config_three_views: "Trois vues",
    config_sticker_collection: "Collection de stickers",
    config_sticker_collection_count: "Stickers par image",
    config_sticker_collection_hint: "Génère plusieurs petits stickers ensemble sur une planche cohérente.",
    config_sticker_border: "Bord blanc",
    config_facial_features: "Générer des visages",
    text_section_title: "Texte",
    background_section_title: "Fond",
    text_enable: "Ajouter du texte ?",
    text_input_placeholder: "Entrez du texte ou laissez vide pour laisser l'IA choisir",
    font_style: "Style de police",
    text_border: "Contour du texte",
    bg_color: "Couleur de fond",
    btn_generate: "Générer les stickers",
    btn_generating: "Création des stickers...",
    gallery_title: "Votre galerie",
    gallery_category_all: "Tous les styles",
    select_all: "Tout sélectionner",
    deselect_all: "Tout désélectionner",
    download_zip: "Télécharger ZIP",
    selected: "Sélectionnés",
    zipping: "Compression...",
    empty_gallery_title: "Prêt à créer ?",
    empty_gallery_desc: "Entrez un prompt et choisissez un style pour générer vos premiers stickers.",
    error_generic: "Une erreur est survenue lors de la génération. Réessayez.",
    sticker_details: "Détails du sticker",
    created: "Créé",
    download_png: "Télécharger PNG",
    custom_style_name: "Mon style",
    action_delete: "Supprimer",
    action_regenerate: "Régénérer / Remix",
    action_clear_image: "Effacer l'image",
    prompt_generator_title: "Générateur de prompts",
    prompt_generator_placeholder: "Entrez une catégorie (ex. 'Plantes', 'Fast-food')",
    prompt_generator_btn: "Générer la liste",
    prompt_generator_use: "Utiliser ceci",
    upload_image_title: "Importer dans la galerie",
    upload_image_desc: "Ajoutez votre propre image à la galerie.",
    upload_image_classification: "Classification / Style",
    upload_image_prompt: "Description / Prompt",
    btn_upload: "Importer",
    btn_uploading: "Importation...",
  },
  de: {
    title_suffix: "Craft",
    subtitle: "KI-Generator",
    powered_by: "Bereitgestellt von Gemini",
    hero_title_1: "Mach Ideen zu",
    hero_title_2: "Stickern",
    hero_desc: "Erstelle in Sekunden einzigartige Sticker im Cartoon-Stil mit KI.",
    prompt_label: "Was möchtest du erstellen?",
    prompt_placeholder: "Gib pro Zeile einen Prompt ein...\nZ. B.:\nEin fröhlicher kleiner Fuchs\nEine Flotte U-Boote",
    prompt_presets: "Probiere das:",
    style_label: "Stil wählen",
    style_custom_count: "Benutzerdefiniert",
    style_custom_remove: "Stil entfernen",
    style_import: "Eigenen Stil erstellen",
    style_modifier: "Stilbeschreibung",
    style_analyzed: "Analysierte Stilbeschreibung",
    style_my: "MEIN",
    create_style_title: "Neuen Stil erstellen",
    style_desc_placeholder: "Beschreibe den Stil (z. B. 'Aquarell, sanfte Pastellfarben, verträumt')...",
    upload_reference: "Referenzbild hochladen (optional)",
    btn_create_style: "Stil speichern",
    btn_creating_style: "Analysiere und speichere...",
    style_creation_error: "Bitte gib eine Beschreibung oder ein Bild an.",
    style_image_analyzed: "Bild erfolgreich analysiert.",
    config_quantity: "Anzahl",
    config_ratio: "Format",
    config_model: "Modell",
    config_resolution: "Auflösung",
    config_layout_mode: "Layoutmodus",
    config_single_sticker: "Einzelsticker",
    config_three_views: "Drei Ansichten",
    config_sticker_collection: "Sticker-Sammlung",
    config_sticker_collection_count: "Sticker pro Bild",
    config_sticker_collection_hint: "Erzeugt mehrere kleine Sticker gemeinsam auf einem stimmigen Bogen.",
    config_sticker_border: "Weißer Rand",
    config_facial_features: "Gesichter erzeugen",
    text_section_title: "Text",
    background_section_title: "Hintergrund",
    text_enable: "Text hinzufügen?",
    text_input_placeholder: "Text eingeben oder leer lassen, damit die KI wählt",
    font_style: "Schriftstil",
    text_border: "Textrand",
    bg_color: "Hintergrundfarbe",
    btn_generate: "Sticker generieren",
    btn_generating: "Sticker werden erstellt...",
    gallery_title: "Deine Galerie",
    gallery_category_all: "Alle Stile",
    select_all: "Alle auswählen",
    deselect_all: "Auswahl aufheben",
    download_zip: "ZIP herunterladen",
    selected: "Ausgewählt",
    zipping: "Komprimiere...",
    empty_gallery_title: "Bereit zum Erstellen?",
    empty_gallery_desc: "Gib einen Prompt ein und wähle einen Stil, um deine ersten Sticker zu generieren.",
    error_generic: "Beim Generieren ist ein Fehler aufgetreten. Bitte erneut versuchen.",
    sticker_details: "Sticker-Details",
    created: "Erstellt",
    download_png: "PNG herunterladen",
    custom_style_name: "Mein Stil",
    action_delete: "Löschen",
    action_regenerate: "Neu generieren / Remix",
    action_clear_image: "Bild entfernen",
    prompt_generator_title: "Prompt-Generator",
    prompt_generator_placeholder: "Kategorie eingeben (z. B. 'Pflanzen', 'Fast Food')",
    prompt_generator_btn: "Liste generieren",
    prompt_generator_use: "Diese verwenden",
    upload_image_title: "In Galerie hochladen",
    upload_image_desc: "Füge dein eigenes Bild zur Galerie hinzu.",
    upload_image_classification: "Klassifizierung / Stil",
    upload_image_prompt: "Beschreibung / Prompt",
    btn_upload: "Hochladen",
    btn_uploading: "Lade hoch...",
  },
  ja: {
    title_suffix: "Craft",
    subtitle: "AI ジェネレーター",
    powered_by: "Gemini 搭載",
    hero_title_1: "アイデアを",
    hero_title_2: "ステッカーに",
    hero_desc: "高度な AI で、ユニークなカートゥーン風ステッカーを数秒で作成できます。",
    prompt_label: "何を作りますか？",
    prompt_placeholder: "1行に1つずつプロンプトを入力...\n例:\n楽しい子ぎつね\n潜水艦の艦隊",
    prompt_presets: "試してみる:",
    style_label: "スタイルを選択",
    style_custom_count: "カスタム",
    style_custom_remove: "スタイルを削除",
    style_import: "カスタムスタイルを作成",
    style_modifier: "スタイル修飾",
    style_analyzed: "解析されたスタイル説明",
    style_my: "MY",
    create_style_title: "新しいスタイルを作成",
    style_desc_placeholder: "スタイルを説明 (例: '水彩、柔らかなパステル、夢のような雰囲気')...",
    upload_reference: "参考画像をアップロード (任意)",
    btn_create_style: "スタイルを保存",
    btn_creating_style: "解析して保存中...",
    style_creation_error: "説明または画像を指定してください。",
    style_image_analyzed: "画像の解析が完了しました。",
    config_quantity: "数量",
    config_ratio: "比率",
    config_model: "モデル",
    config_resolution: "解像度",
    config_layout_mode: "レイアウト",
    config_single_sticker: "単体ステッカー",
    config_three_views: "三面図",
    config_sticker_collection: "ステッカーコレクション",
    config_sticker_collection_count: "1枚あたりの数",
    config_sticker_collection_hint: "複数の小さなステッカーを1枚の統一されたシートに生成します。",
    config_sticker_border: "白いステッカー枠",
    config_facial_features: "顔を生成",
    text_section_title: "文字",
    background_section_title: "背景",
    text_enable: "文字を追加？",
    text_input_placeholder: "文字を入力、または空欄でAIに任せる",
    font_style: "フォント",
    text_border: "文字の縁取り",
    bg_color: "背景色",
    btn_generate: "ステッカーを生成",
    btn_generating: "ステッカーを作成中...",
    gallery_title: "ギャラリー",
    gallery_category_all: "すべてのスタイル",
    select_all: "すべて選択",
    deselect_all: "選択解除",
    download_zip: "ZIP をダウンロード",
    selected: "選択中",
    zipping: "圧縮中...",
    empty_gallery_title: "作成を始めますか？",
    empty_gallery_desc: "プロンプトを入力し、スタイルを選んで最初のステッカーを生成しましょう。",
    error_generic: "生成中に問題が発生しました。もう一度お試しください。",
    sticker_details: "ステッカー詳細",
    created: "作成日時",
    download_png: "PNG をダウンロード",
    custom_style_name: "マイスタイル",
    action_delete: "削除",
    action_regenerate: "再生成 / リミックス",
    action_clear_image: "画像をクリア",
    prompt_generator_title: "プロンプト生成",
    prompt_generator_placeholder: "カテゴリを入力 (例: '植物', 'ファストフード')",
    prompt_generator_btn: "リスト生成",
    prompt_generator_use: "これを使う",
    upload_image_title: "ギャラリーに追加",
    upload_image_desc: "自分の画像をギャラリーに追加します。",
    upload_image_classification: "分類 / スタイル",
    upload_image_prompt: "説明 / プロンプト",
    btn_upload: "アップロード",
    btn_uploading: "アップロード中...",
  },
  ko: {
    title_suffix: "Craft",
    subtitle: "AI 생성기",
    powered_by: "Gemini 기반",
    hero_title_1: "아이디어를",
    hero_title_2: "스티커로",
    hero_desc: "고급 AI로 독특한 카툰 스타일 스티커를 몇 초 만에 만들어 보세요.",
    prompt_label: "무엇을 만들까요?",
    prompt_placeholder: "한 줄에 하나씩 프롬프트를 입력하세요...\n예:\n행복한 아기 여우\n잠수함 함대",
    prompt_presets: "이것도 좋아요:",
    style_label: "스타일 선택",
    style_custom_count: "사용자 지정",
    style_custom_remove: "스타일 삭제",
    style_import: "사용자 지정 스타일 만들기",
    style_modifier: "스타일 설명",
    style_analyzed: "분석된 스타일 설명",
    style_my: "내",
    create_style_title: "새 스타일 만들기",
    style_desc_placeholder: "스타일을 설명하세요 (예: '수채화, 부드러운 파스텔, 몽환적인 분위기')...",
    upload_reference: "참고 이미지 업로드 (선택)",
    btn_create_style: "스타일 저장",
    btn_creating_style: "분석 및 저장 중...",
    style_creation_error: "스타일을 만들려면 설명 또는 이미지를 제공하세요.",
    style_image_analyzed: "이미지 분석 완료!",
    config_quantity: "수량",
    config_ratio: "비율",
    config_model: "모델",
    config_resolution: "해상도",
    config_layout_mode: "레이아웃 모드",
    config_single_sticker: "단일 스티커",
    config_three_views: "3면도",
    config_sticker_collection: "스티커 컬렉션",
    config_sticker_collection_count: "이미지당 스티커 수",
    config_sticker_collection_hint: "여러 작은 스티커를 하나의 통일된 시트로 생성합니다.",
    config_sticker_border: "흰색 스티커 테두리",
    config_facial_features: "얼굴 생성",
    text_section_title: "텍스트",
    background_section_title: "배경",
    text_enable: "텍스트 추가?",
    text_input_placeholder: "텍스트를 입력하거나 비워 두면 AI가 선택합니다",
    font_style: "글꼴 스타일",
    text_border: "텍스트 테두리",
    bg_color: "배경색",
    btn_generate: "스티커 생성",
    btn_generating: "스티커 제작 중...",
    gallery_title: "내 갤러리",
    gallery_category_all: "모든 스타일",
    select_all: "전체 선택",
    deselect_all: "선택 해제",
    download_zip: "ZIP 다운로드",
    selected: "선택됨",
    zipping: "압축 중...",
    empty_gallery_title: "만들 준비가 됐나요?",
    empty_gallery_desc: "프롬프트를 입력하고 스타일을 선택해 첫 스티커를 생성하세요.",
    error_generic: "스티커 생성 중 문제가 발생했습니다. 다시 시도하세요.",
    sticker_details: "스티커 상세",
    created: "생성일",
    download_png: "PNG 다운로드",
    custom_style_name: "내 스타일",
    action_delete: "삭제",
    action_regenerate: "재생성 / 리믹스",
    action_clear_image: "이미지 지우기",
    prompt_generator_title: "프롬프트 생성기",
    prompt_generator_placeholder: "카테고리 입력 (예: '식물', '패스트푸드')",
    prompt_generator_btn: "목록 생성",
    prompt_generator_use: "사용하기",
    upload_image_title: "갤러리에 업로드",
    upload_image_desc: "내 이미지를 갤러리에 추가합니다.",
    upload_image_classification: "분류 / 스타일",
    upload_image_prompt: "설명 / 프롬프트",
    btn_upload: "업로드",
    btn_uploading: "업로드 중...",
  },
  pt: {
    title_suffix: "Craft",
    subtitle: "Gerador de IA",
    powered_by: "Com Gemini",
    hero_title_1: "Transforme ideias em",
    hero_title_2: "Stickers",
    hero_desc: "Crie stickers únicos em estilo cartoon em segundos com IA avançada.",
    prompt_label: "O que você quer criar?",
    prompt_placeholder: "Digite um prompt por linha para gerar em lote...\nEx.:\nUma raposinha feliz\nUma frota de submarinos",
    prompt_presets: "Experimente:",
    style_label: "Escolha um estilo",
    style_custom_count: "Personalizado",
    style_custom_remove: "Remover estilo",
    style_import: "Criar estilo personalizado",
    style_modifier: "Modificador de estilo",
    style_analyzed: "Descrição de estilo analisada",
    style_my: "MEU",
    create_style_title: "Criar novo estilo",
    style_desc_placeholder: "Descreva o estilo (ex. 'aquarela, tons pastel suaves, clima sonhador')...",
    upload_reference: "Enviar imagem de referência (opcional)",
    btn_create_style: "Salvar estilo",
    btn_creating_style: "Analisando e salvando...",
    style_creation_error: "Forneça uma descrição ou imagem para criar um estilo.",
    style_image_analyzed: "Imagem analisada com sucesso.",
    config_quantity: "Quantidade",
    config_ratio: "Proporção",
    config_model: "Modelo",
    config_resolution: "Resolução",
    config_layout_mode: "Modo de layout",
    config_single_sticker: "Sticker único",
    config_three_views: "Três vistas",
    config_sticker_collection: "Coleção de stickers",
    config_sticker_collection_count: "Stickers por imagem",
    config_sticker_collection_hint: "Gera vários stickers pequenos juntos em uma folha coesa.",
    config_sticker_border: "Borda branca",
    config_facial_features: "Gerar rostos",
    text_section_title: "Texto",
    background_section_title: "Fundo",
    text_enable: "Adicionar texto?",
    text_input_placeholder: "Digite o texto ou deixe em branco para a IA escolher",
    font_style: "Estilo da fonte",
    text_border: "Borda do texto",
    bg_color: "Cor de fundo",
    btn_generate: "Gerar stickers",
    btn_generating: "Criando stickers...",
    gallery_title: "Sua galeria",
    gallery_category_all: "Todos os estilos",
    select_all: "Selecionar tudo",
    deselect_all: "Desmarcar tudo",
    download_zip: "Baixar ZIP",
    selected: "Selecionados",
    zipping: "Compactando...",
    empty_gallery_title: "Pronto para criar?",
    empty_gallery_desc: "Digite um prompt e escolha um estilo para gerar seus primeiros stickers.",
    error_generic: "Algo deu errado ao gerar stickers. Tente novamente.",
    sticker_details: "Detalhes do sticker",
    created: "Criado",
    download_png: "Baixar PNG",
    custom_style_name: "Meu estilo",
    action_delete: "Excluir",
    action_regenerate: "Regenerar / Remix",
    action_clear_image: "Limpar imagem",
    prompt_generator_title: "Gerador de prompts",
    prompt_generator_placeholder: "Digite uma categoria (ex. 'Plantas', 'Fast food')",
    prompt_generator_btn: "Gerar lista",
    prompt_generator_use: "Usar estes",
    upload_image_title: "Enviar para galeria",
    upload_image_desc: "Adicione sua própria imagem à galeria.",
    upload_image_classification: "Classificação / Estilo",
    upload_image_prompt: "Descrição / Prompt",
    btn_upload: "Enviar",
    btn_uploading: "Enviando...",
  }
};
